### ISSUE TITLE
Issue in Keywords-&-Language-Features

### ISSUE THREAD

**Issue by 0797cjm** [505e06b2/MW2-GSC-Documentation#1]
Was browsing the documentation and I clicked "Keyword & Language Features" and it said "If you see this create an issue" so here I am.
https://github.com/505e06b2/MW2-GSC-Documentation/wiki/Keywords-&-Language-Features

**Comment by 505e06b2** [comment]
I should be able to get this started tonight; is there anything you're specifically looking for?

**Comment by 0797cjm** [comment]
> I should be able to get this started tonight; is there anything you're specifically looking for?

Basically just looking for references to teach myself gsc.

**Comment by 505e06b2** [comment]
I think the best way, for the moment, might be to check out other people's menus/games since I'm probably going to be pretty lazy lol
The scripts I was working on in 2020-ish are now up on Github https://github.com/505e06b2/EbinModz

**Comment by 0797cjm** [comment]
Thank you. That is currently what I am doing but there isn’t much in the sense of explanations for certain things. Little but important things. I know cod4 and waw are similar but not sure which one would be best to use as a guide. Would love something explaining arrays, shaders, dvar usage, etc. do you know if any such documentation?

Cody J Moores
________________________________

**Comment by 0797cjm** [comment]
> 

I’ve been all over the web looking at different index’s, wikis, docs, archived forums, old codes, menus. It’s pretty complex for someone refreshing their mind. I haven’t seen a simple one yet to build my knowledge on and I’m not sure which parts I can tinker with yet

**Comment by 0797cjm** [comment]
I guess a better question would be, which language would you suggest to learn to grasp the fundamentals? I checked out your mod and it’s amazing. Especially where it’s made for pc. I’m going to study every part. You seem to have a firm understanding. Are you able to point me in the right direction? 

Add me on discord if you’d like and willing so I don’t need to msg you through here

**Comment by 505e06b2** [comment]
>I know cod4 and waw are similar but not sure which one would be best to use as a guide

It seems like every year they tinkered with GSC, but the documentation online seems better for CoD4 - it may help to grasp the fundamentals, especially Zeroy's site: https://wiki.zeroy.com/index.php?title=Call_of_Duty_4:_Introduction

>I’ve been all over the web looking at different index’s, wikis, docs, archived forums, old codes, menus. It’s pretty complex for someone refreshing their mind

To be honest, I've kinda lost the grasp on the language that I had since it's been so long since I worked on EbinModz... What I did find is that most of the code written that's online is terrible... I need to have a look over mine and see how bad it is/improve it lol

>I guess a better question would be, which language would you suggest to learn to grasp the fundamentals?

GSC-wise I'd recommend CoD4, but if you have experience with Javascript, C++ or C#, I think that could help - Javascript being the easiest to get running (just pop open a browser window lol)

I'll give you an add on Discord (I think it may be incorrect on your profile?)

**Comment by 0797cjm** [comment]
Thank you for your help! So much appreciated. My discord is Random Guy 70hz#2299

Cody J Moores
________________________________
